dist: trusty
language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: ceciliacal
    token: 331a1df367982550e16360321497cab14c6a817e

     
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn compile sonar:sonar  -Dsonar.projectKey=ceciliacal_bookkeeper -Ppit  -Dmaven.javadoc.skip=true

  # - mvn clean -DskipTests
